version: '3.8'
services:
  backend:
    build:
      context: ../backend
    env_file:
      - ../backend/.env
    ports:
      - "5001:5001"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=${NODE_ENV}
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
  frontend:
    build:
      context: ../frontend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=${NODE_ENV}
      - BACKEND_URL=${BACKEND_URL}
  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
